name: release

# Controls when the workflow will run
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Download rfmp
        uses: robinraju/release-downloader@v1.7
        with:
          repository: JohnTheCoolingFan/rfmp
          fileName: rfmp-linux
          latest: true
      
      - name: Get full mod file name
        run: |
          MFNAME=$(jq -r '.name + "_" + .version + ".zip"' info.json)
          echo "MODFILENAME=$MFNAME" >> $GITHUB_ENV

      - name: Pack a mod
        run: |
          chmod +x ./rfmp-linux
          ./rfmp-linux --no-clean --install-dir .
      
      - name: Upload file to release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.MODFILENAME }}

      - name: Publish mod on mod portal
        uses: JohnTheCoolingFan/factorio-mod-publish@v3
        with:
          factorio_token: ${{ secrets.FACTORIO_TOKEN }}

      - name: Send notification on Discord
        uses: JohnTheCoolingFan/factorio-mod-discord-announce@v4
        with:
          discord_webhook: ${{ secrets.DISCORD_NEW_WEBHOOK }}
