name: release

# Controls when the workflow will run
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Download rfmp
        uses: robinraju/release-downloader@v1.7
        with:
          repository: JohnTheCoolingFan/rfmp
          fileName: rfmp-linux
      
      - name: Get full mod file name
        run: |
          MFNAME=$(jq -r '.name + "_" + .version + ".zip"' info.json)
          echo "MODFILENAME=$MFNAME" >> $GITHUB_ENV

      - name: Pack a mod
        run: |
          chmod +x ./rfmp-linux
          ./rfmp-linux --no-clean --install-dir .
        
      - name: Upload packed mod as an artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: packed-mod
          path: ./${{ env.MODFILENAME }}
      
      - name: Upload mod name as an artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: info-json
          path: info.json
        
  release-github:
    name: Release on github
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download mod
        uses: actions/download-artifact@v3.0.2
        with:
          name: packed-mod
      
      - name: Download info.json
        uses: actions/download-artifact@v3.0.2
        with:
          name: info-json
      
      - name: Set up environment and file names
        run: |
          MFNAME=$(jq -r '.name + "_" + .version + ".zip"' info.json)
          echo "MODFILENAME=$MFNAME" >> $GITHUB_ENV
      
      - name: Upload file to release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.MODFILENAME }}
